export const voicePrompt = "An American male painting teacher, 45 to 60, with a gentle Southern accent, warm mid-low pitch, soft breathy resonance and a faint velvety rasp. Very quiet, intimate, close-microphone delivery, slow unhurried pacing, tender rising and falling intonation, relaxed consonants and a small smile in the voice. Calm, reassuring and conversational, with room to breathe between thoughts. Ideal for an ASMR oil-painting lesson explaining delicate brush strokes.";
export const audition = "A little blue on the brush. Nice and easy. We'll leave a little light between those trees.";
export const chapters = [
  { id: "ground", title: "A little colour to begin", paint: "Wide brush · Thin colour", text: "Well, hello there. I'm Bob Loss. Let's turn your photograph into a little painting... We'll start with a wide brush. Big patches of colour, nice and loose. Nothing needs to look like anything just yet. We're only giving the paint somewhere to go." },
  { id: "planes", title: "Let the shapes settle", paint: "Broad strokes · Gentle pressure", text: "There we go... Let those colours sit beside each other. A light patch here, a darker one there. Keep your hand relaxed. If a little of the canvas peeks through, that's perfectly fine. We'll leave it a little room to breathe." },
  { id: "forms", title: "Find the familiar shapes", paint: "Flat brush · Overlapping marks", text: "Now we're beginning to find the shapes in your photograph. A slightly smaller brush this time... Lay one mark beside another. You don't have to describe every little thing. Sometimes a few colours together tell you quite a lot." },
  { id: "edges", title: "A few clearer edges", paint: "Turn the brush · Follow the form", text: "Let's give a few of those edges a little attention. Turn the brush as the shape turns. Softly now... Some edges can stay blurry. Others need a firmer touch. It gives your eye something to follow, without making every part of the painting shout." },
  { id: "colour", title: "Keep some warmth in it", paint: "Small brush · Warm and cool", text: "Look at those little changes in colour. A warm touch next to a cool one... We can leave the strokes showing. I rather like seeing how a painting was made. It's a bit like finding footprints on a path. You can see where someone has been." },
  { id: "accents", title: "Let the little details arrive", paint: "Short strokes · Light touches", text: "Just a few smaller marks now. The places where light meets dark... Easy does it. There's no need to polish all the life out of it. If a brushstroke wanders a little, we'll let it stay. It might know a nice place to go." },
  { id: "texture", title: "Leave a little brushwork", paint: "Dry bristles · Broken colour", text: "We'll drag the bristles very lightly across a few of those shapes. See how the colour breaks? That's the texture we want... A little roughness, a little movement. Your photograph gave us a place to begin. The paint gets to have a say too." },
  { id: "finish", title: "A painting to keep", paint: "Final accents · Leave it loose", text: "One or two finishing touches... And there we are. A little painting of your own. You can save it, share it, or bring another photograph and we'll paint together again... Thank you for spending a little time with me." }
];
